### ISSUE TITLE
Accessibility Docs

### ISSUE THREAD

**Issue by TouchstoneTheGreat** [FirebaseExtended/ai-extensions-codelab#2]
I want to contribute by adding text to docs. that users can access the project's directly from codespaces. Can submit pr for that. Pretty plz 🥺
Can you tell me what are guidelines ? (asking Because when i contributed to Microsoft they Deleted all lines and then closed PR.)

PS: PR will/can be

Users can try the demos, examples, templates by simple clicking Code < > button -> then click on Codespaces -> and then click + button.

**Comment by nohe427** [comment]
I would rather not add instructions on how to use GitHub codespaces to the README as that is beyond the scope of the README for this repository.  If users are interested in understanding how to get started with GitHub Codespaces, they can always visit [this documentation](https://docs.github.com/en/codespaces/getting-started/quickstart).
